api_keys:
  twitter:
    api_key: ""
    api_secret: ""
  instagram:
    access_token: ""
  shopify:
    api_key: ""
    shop_url: ""
  google_analytics: "your_ga_api_key"

agents:
  market_research:
    enabled: true
    schedule: "0 8 * * *"
    tools:
      - web_search_tool
      - file_search_tool

  audience_segmentation:
    enabled: true
    schedule: "30 0 * * *"
    tools:
      - crm_tool

  content_creation:
    enabled: true
    max_retries: 3
    character_limits:
      twitter: 280
      instagram: 2200
      tiktok: 150

# ... other agent configs

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

guardrails:
  rate_limits:
    twitter_posts_per_hour: 5
    instagram_posts_per_day: 10

schedules:
  market_research: "0 8 * * *"  # daily @ 08:00
  audience_segmentation: "30 0 * * *"  # daily @ 00:30
  # ... other schedules

feature_flags:
  enable_auto_posting: true
  enable_auto_replies: true
  # ... other flags

limits:
  twitter_char_limit: 280
  instagram_caption_limit: 2200
  # ... other limits 